### ISSUE TITLE
(9.7.10) mod fails to import laws/districts

### ISSUE THREAD

**Issue by padmanek** [thomasfn/EcoCivicsImportExportMod#64]
This error is thrown into server console when attempting to.
```
[19:05:21.399] [16] [ Info] [Eco] [CivicsImpExpPlugin] ERROR: Failed to import stub for civic DistrictMap:"District Map": System.MissingMethodException: Attempted to access a missing method.
   at Eco.Mods.CivicsImpExp.BundledCivic.CreateStub()
   at Eco.Mods.CivicsImpExp.ImportContext.ImportStub(BundledCivic bundledCivic)
   at Eco.Mods.CivicsImpExp.CivicBundle.ImportAll(Settlement settlement)
```

**Comment by thomasfn** [comment]
Addressed in [0.6.3](https://github.com/thomasfn/EcoCivicsImportExportMod/releases/tag/0.6.3)
